owner: urbnshire
repo: observability

sites:
  - name: designova
    url: https://designova.netlify.app/
    assignees:
      - AryaaMadhur
      - urbnshire
  - name: Fewv
    url: https://fewv.dev/
    assignees:
      - Vishakha-Sawra

status-website:
  name: observability
  theme: light
  baseUrl: /observability
  logoUrl: https://raw.githubusercontent.com/urbnshire/observability/master/assets/upptime-icon.svg
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/urbnshire/observability
